"""Delete username field

Revision ID: 6bdf8e7f62ba
Revises: d4f3eb42887f
Create Date: 2023-09-07 17:17:10.557662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdf8e7f62ba'
down_revision = 'd4f3eb42887f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
